### ISSUE TITLE
✨ Convenience method - shortenUsing

### ISSUE THREAD

**Issue by axlon** [LaraCrafts/laravel-url-shortener#11]
`UrlShortener::shortenUsing($driver, $url, $options)` which would allow shortening using any non-default driver without first having to retrieve said driver

**Comment by axlon** [comment]
I (temporarily) closed #15 which handles this, I think we aren't in agreement yet as to how/where this should be added

**Comment by nerg4l** [comment]
I would keep extending the `Url` facade (`UrlGenerator`) and remove `UrlShortener` facade. To add an other driver the developer would need to use the DI to access `UrlShortenerManager`.
