### ISSUE TITLE
🔧 Use less environment variables

### ISSUE THREAD

**Issue by nerg4l** [LaraCrafts/laravel-url-shortener#14]
Gathered the following from the slack discussion:

Currently the library uses different environment variables for bit.ly, firebase, is.gd, etc. The same variable could be used for multiple drivers. eg `SHORTENER_API_KEY` instead of `BIT_LY_API_KEY` and `OUO_IO_API_TOKEN`.

PRO:

- A lot of "namespaces" is used right now as far as environment variables are concerned
- The library have 6 drivers and 9 variables. 
- The developer can modify the config file for more flexibility same as databases do.

CONTRA:

- This would be annoying if you use multiple services. By having them named differently you can use multiple drivers within the same app.
- This would not work nicely with #12 
- Generalising the environment variables would limit flexibility unless the programmer edits the config manually.

The question is how people intend to use it. They try to stick with one "connection" or they use multiple of them.

**Comment by nerg4l** [comment]
Proposed changes:

- `SHORTENER_API_KEY` would replace `BIT_LY_API_TOKEN`, `FIREBASE_API_TOKEN`, `OUO_IO_API_TOKEN` and `SHORTE_ST_API_TOKEN`
- `SHORTENER_DOMAIN` would replace `BIT_LY_DOMAIN`, `FIREBASE_URI_PREFIX` and the upcoming variable for Polr
- `FIREBASE_SUFFIX`, `IS_GD_LINK_PREVIEWS`, `IS_GD_STATISTICS` would become configurations which can be modified via publishing and editing the config file

**Comment by axlon** [comment]
After giving it some thought, I agree. I'll include this in the #12 PR

**Comment by nerg4l** [comment]
After a short discussion instead of `SHORTENER_` we decided to use `URL_SHORTENER_` as the prefix.

**Comment by nerg4l** [comment]
Resolved by #18
