### ISSUE TITLE
🏎 Laravel driver

### ISSUE THREAD

**Issue by axlon** [LaraCrafts/laravel-url-shortener#19]
I've been playing with the idea of adding a "local" driver which runs on the application's own database.

This would driver would probably have a considerable footprint compared to the rest of the package so perhaps if we decide to implement this, it should be a separate package.

**Comment by ash-jc-allen** [comment]
Hi guys! I saw your post on Reddit and thought I'd try and offer a bit of help! 😄

I've already got a package which I think would fit nicely with the ``` local ``` driver. If it looks the kind of thing you might want to implement for it, I'd be happy to maybe take a look and add the ``` local ``` driver implementation myself for you?

https://github.com/ash-jc-allen/short-url

**Comment by axlon** [comment]
Hi @ash-jc-allen sorry for the slow reply!

Thank you for your interest in contributing, feel free to write a driver for your package and we will be sure to include it! The more the merrier the way we see it.

**Comment by ash-jc-allen** [comment]
Hi @axlon it's no problem at all!

I'm a bit busy for the next few weeks but I'd be happy to take a go at writing a driver for it after that! Thanks for giving me the chance to contribute :)
