### ISSUE TITLE
🤖 Test overhaul

### ISSUE THREAD

**Issue by axlon** [LaraCrafts/laravel-url-shortener#20]
- [x] Travis CI config overhaul (#21)
- [ ] Bit.ly driver unit tests
- [ ] Firebase driver unit tests
- [x] Is.gd / V.gd driver unit tests
- [ ] Ouo.io driver unit tests
- [x] Shorte.st driver unit tests
- [x] TinyURL driver unit tests
- [x] Polr driver unit tests

**Comment by axlon** [comment]
@nerg4l would it be an idea to also add a integration test for Polr, for master only?

**Comment by nerg4l** [comment]
@axlon Polr is a self-hosted service so to be able to run an integration test we need to host. Of course I can add an integration test which is protected by environment variables as the others so it will never run.

**Comment by axlon** [comment]
I was thinking maybe we can spin up a Polr environment during the Travis build and test against that.

**Comment by nerg4l** [comment]
@axlon I will need some help with that
