### ISSUE TITLE
Feature Request: Custom drivers

### ISSUE THREAD

**Issue by Braunson** [LaraCrafts/laravel-url-shortener#3]
It would be nice to support custom drivers somehow. :)

**Comment by yak0d3** [comment]
This package uses the Laravel Manager approach, so you can easily extend the `UrlShortenerManager` by using the `extend($driver, Closure $callback)` method.
e.g:
```
app('url.shortener')->extend('custom', function () { return new CustomDriver($client, $token); });
```
You may easily create a new driver by extending the abstract `LaraCrafts\UrlShortener\Http\RemoteShortener` and implementing your own driver logic in the `shortenAsync` method.

**Comment by axlon** [comment]
@Braunson Thanks for the issue report, like @yak0d3 said this can already easily be done by registering your own driver to the `UrlShortenerManager`. I will add this to the readme, because this feature wasn't yet documented.
